//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMethod", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class PaymentMethod : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingMethod", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class ShippingMethod : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class Products : object
    {
        
        private bool AvailableField;
        
        private int CategoryIdField;
        
        private string CategoryNameField;
        
        private string FullDescriptionField;
        
        private int IdField;
        
        private int ManufacturerIdField;
        
        private string ManufacturerNameField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private string SKUField;
        
        private string ShortDescriptionField;
        
        private string UrlPictureField;
        
        private string UrlProductField;
        
        private decimal VatField;
        
        private decimal YourPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Available
        {
            get
            {
                return this.AvailableField;
            }
            set
            {
                this.AvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullDescription
        {
            get
            {
                return this.FullDescriptionField;
            }
            set
            {
                this.FullDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManufacturerId
        {
            get
            {
                return this.ManufacturerIdField;
            }
            set
            {
                this.ManufacturerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerName
        {
            get
            {
                return this.ManufacturerNameField;
            }
            set
            {
                this.ManufacturerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU
        {
            get
            {
                return this.SKUField;
            }
            set
            {
                this.SKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription
        {
            get
            {
                return this.ShortDescriptionField;
            }
            set
            {
                this.ShortDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlPicture
        {
            get
            {
                return this.UrlPictureField;
            }
            set
            {
                this.UrlPictureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlProduct
        {
            get
            {
                return this.UrlProductField;
            }
            set
            {
                this.UrlProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Vat
        {
            get
            {
                return this.VatField;
            }
            set
            {
                this.VatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal YourPrice
        {
            get
            {
                return this.YourPriceField;
            }
            set
            {
                this.YourPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceCategory", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class WebServiceCategory : object
    {
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private int ParentCategoryIdField;
        
        private bool PublishedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentCategoryId
        {
            get
            {
                return this.ParentCategoryIdField;
            }
            set
            {
                this.ParentCategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published
        {
            get
            {
                return this.PublishedField;
            }
            set
            {
                this.PublishedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceManufacturer", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class WebServiceManufacturer : object
    {
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private bool PublishedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Published
        {
            get
            {
                return this.PublishedField;
            }
            set
            {
                this.PublishedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class Address : object
    {
        
        private string Address1Field;
        
        private string CityField;
        
        private string CompanyField;
        
        private int CountryIdField;
        
        private string CountryNameField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private int StateProvinceIdField;
        
        private string StateProvinceNameField;
        
        private string ZipPostalCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateProvinceId
        {
            get
            {
                return this.StateProvinceIdField;
            }
            set
            {
                this.StateProvinceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvinceName
        {
            get
            {
                return this.StateProvinceNameField;
            }
            set
            {
                this.StateProvinceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipPostalCode
        {
            get
            {
                return this.ZipPostalCodeField;
            }
            set
            {
                this.ZipPostalCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAddressResult", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class CreateAddressResult : object
    {
        
        private int IdField;
        
        private string MessageField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductAttributes", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class ProductAttributes : object
    {
        
        private int ProductAttributeIdField;
        
        private string ProductAttributeValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductAttributeId
        {
            get
            {
                return this.ProductAttributeIdField;
            }
            set
            {
                this.ProductAttributeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductAttributeValue
        {
            get
            {
                return this.ProductAttributeValueField;
            }
            set
            {
                this.ProductAttributeValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class Cart : object
    {
        
        private decimal DiscountField;
        
        private decimal PriceField;
        
        private decimal PriceWithDiscountField;
        
        private int QuantityField;
        
        private string SKUField;
        
        private decimal TaxRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceWithDiscount
        {
            get
            {
                return this.PriceWithDiscountField;
            }
            set
            {
                this.PriceWithDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU
        {
            get
            {
                return this.SKUField;
            }
            set
            {
                this.SKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxRate
        {
            get
            {
                return this.TaxRateField;
            }
            set
            {
                this.TaxRateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class Country : object
    {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateProvince", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class StateProvince : object
    {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateOrderResult", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class CreateOrderResult : object
    {
        
        private int IdField;
        
        private string MessageField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Orders")]
    public enum OrderStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 40,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Payments")]
    public enum PaymentStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Authorized = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paid = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartiallyRefunded = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refunded = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Voided = 50,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingStatus", Namespace="http://schemas.datacontract.org/2004/07/Nop.Core.Domain.Shipping")]
    public enum ShippingStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShippingNotRequired = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotYetShipped = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartiallyShipped = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shipped = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 40,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceOrder", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class WebServiceOrder : object
    {
        
        private ServiceReference.Address BillingAddressField;
        
        private int BillingAddressIdField;
        
        private string CheckoutAttributeDescriptionField;
        
        private string CheckoutAttributesXmlField;
        
        private System.DateTime CreatedOnUtcField;
        
        private decimal CurrencyRateField;
        
        private string CustomerCurrencyCodeField;
        
        private int CustomerIdField;
        
        private int CustomerLanguageIdField;
        
        private int CustomerTaxDisplayTypeIdField;
        
        private bool DeletedField;
        
        private decimal OrderDiscountField;
        
        private System.Guid OrderGuidField;
        
        private int OrderIdField;
        
        private ServiceReference.WebServiceOrderProductVariant[] OrderProductVariantsField;
        
        private decimal OrderShippingExclTaxField;
        
        private decimal OrderShippingInclTaxField;
        
        private ServiceReference.OrderStatus OrderStatusField;
        
        private decimal OrderSubTotalDiscountExclTaxField;
        
        private decimal OrderSubTotalDiscountInclTaxField;
        
        private decimal OrderSubtotalExclTaxField;
        
        private decimal OrderSubtotalInclTaxField;
        
        private decimal OrderTaxField;
        
        private decimal OrderTotalField;
        
        private System.Nullable<System.DateTime> PaidDateUtcField;
        
        private decimal PaymentMethodAdditionalFeeExclTaxField;
        
        private decimal PaymentMethodAdditionalFeeInclTaxField;
        
        private string PaymentMethodSystemNameField;
        
        private ServiceReference.PaymentStatus PaymentStatusField;
        
        private ServiceReference.Address ShippingAddressField;
        
        private System.Nullable<int> ShippingAddressIdField;
        
        private string ShippingMethodField;
        
        private string ShippingRateComputationMethodSystemNameField;
        
        private ServiceReference.ShippingStatus ShippingStatusField;
        
        private string TaxRatesField;
        
        private string VatNumberField;
        
        private ServiceReference.WebServiceOrderProductVariant[] _orderProductVariantField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Address BillingAddress
        {
            get
            {
                return this.BillingAddressField;
            }
            set
            {
                this.BillingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillingAddressId
        {
            get
            {
                return this.BillingAddressIdField;
            }
            set
            {
                this.BillingAddressIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckoutAttributeDescription
        {
            get
            {
                return this.CheckoutAttributeDescriptionField;
            }
            set
            {
                this.CheckoutAttributeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckoutAttributesXml
        {
            get
            {
                return this.CheckoutAttributesXmlField;
            }
            set
            {
                this.CheckoutAttributesXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc
        {
            get
            {
                return this.CreatedOnUtcField;
            }
            set
            {
                this.CreatedOnUtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrencyRate
        {
            get
            {
                return this.CurrencyRateField;
            }
            set
            {
                this.CurrencyRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCurrencyCode
        {
            get
            {
                return this.CustomerCurrencyCodeField;
            }
            set
            {
                this.CustomerCurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerLanguageId
        {
            get
            {
                return this.CustomerLanguageIdField;
            }
            set
            {
                this.CustomerLanguageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerTaxDisplayTypeId
        {
            get
            {
                return this.CustomerTaxDisplayTypeIdField;
            }
            set
            {
                this.CustomerTaxDisplayTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderDiscount
        {
            get
            {
                return this.OrderDiscountField;
            }
            set
            {
                this.OrderDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrderGuid
        {
            get
            {
                return this.OrderGuidField;
            }
            set
            {
                this.OrderGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.WebServiceOrderProductVariant[] OrderProductVariants
        {
            get
            {
                return this.OrderProductVariantsField;
            }
            set
            {
                this.OrderProductVariantsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderShippingExclTax
        {
            get
            {
                return this.OrderShippingExclTaxField;
            }
            set
            {
                this.OrderShippingExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderShippingInclTax
        {
            get
            {
                return this.OrderShippingInclTaxField;
            }
            set
            {
                this.OrderShippingInclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.OrderStatus OrderStatus
        {
            get
            {
                return this.OrderStatusField;
            }
            set
            {
                this.OrderStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderSubTotalDiscountExclTax
        {
            get
            {
                return this.OrderSubTotalDiscountExclTaxField;
            }
            set
            {
                this.OrderSubTotalDiscountExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderSubTotalDiscountInclTax
        {
            get
            {
                return this.OrderSubTotalDiscountInclTaxField;
            }
            set
            {
                this.OrderSubTotalDiscountInclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderSubtotalExclTax
        {
            get
            {
                return this.OrderSubtotalExclTaxField;
            }
            set
            {
                this.OrderSubtotalExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderSubtotalInclTax
        {
            get
            {
                return this.OrderSubtotalInclTaxField;
            }
            set
            {
                this.OrderSubtotalInclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderTax
        {
            get
            {
                return this.OrderTaxField;
            }
            set
            {
                this.OrderTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderTotal
        {
            get
            {
                return this.OrderTotalField;
            }
            set
            {
                this.OrderTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PaidDateUtc
        {
            get
            {
                return this.PaidDateUtcField;
            }
            set
            {
                this.PaidDateUtcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentMethodAdditionalFeeExclTax
        {
            get
            {
                return this.PaymentMethodAdditionalFeeExclTaxField;
            }
            set
            {
                this.PaymentMethodAdditionalFeeExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentMethodAdditionalFeeInclTax
        {
            get
            {
                return this.PaymentMethodAdditionalFeeInclTaxField;
            }
            set
            {
                this.PaymentMethodAdditionalFeeInclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethodSystemName
        {
            get
            {
                return this.PaymentMethodSystemNameField;
            }
            set
            {
                this.PaymentMethodSystemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.PaymentStatus PaymentStatus
        {
            get
            {
                return this.PaymentStatusField;
            }
            set
            {
                this.PaymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Address ShippingAddress
        {
            get
            {
                return this.ShippingAddressField;
            }
            set
            {
                this.ShippingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShippingAddressId
        {
            get
            {
                return this.ShippingAddressIdField;
            }
            set
            {
                this.ShippingAddressIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingMethod
        {
            get
            {
                return this.ShippingMethodField;
            }
            set
            {
                this.ShippingMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingRateComputationMethodSystemName
        {
            get
            {
                return this.ShippingRateComputationMethodSystemNameField;
            }
            set
            {
                this.ShippingRateComputationMethodSystemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.ShippingStatus ShippingStatus
        {
            get
            {
                return this.ShippingStatusField;
            }
            set
            {
                this.ShippingStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxRates
        {
            get
            {
                return this.TaxRatesField;
            }
            set
            {
                this.TaxRatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VatNumber
        {
            get
            {
                return this.VatNumberField;
            }
            set
            {
                this.VatNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.WebServiceOrderProductVariant[] _orderProductVariant
        {
            get
            {
                return this._orderProductVariantField;
            }
            set
            {
                this._orderProductVariantField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceOrderProductVariant", Namespace="http://schemas.datacontract.org/2004/07/Nop.Plugin.Misc.WebServicesCustomer")]
    public partial class WebServiceOrderProductVariant : object
    {
        
        private string AttributeDescriptionField;
        
        private string AttributesXmlField;
        
        private decimal DiscountAmountExclTaxField;
        
        private decimal DiscountAmountInclTaxField;
        
        private System.Nullable<decimal> ItemWeightField;
        
        private int OrderIdField;
        
        private decimal PriceExclTaxField;
        
        private decimal PriceInclTaxField;
        
        private int ProductIdField;
        
        private int QuantityField;
        
        private string SKUField;
        
        private decimal UnitPriceExclTaxField;
        
        private decimal UnitPriceInclTaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeDescription
        {
            get
            {
                return this.AttributeDescriptionField;
            }
            set
            {
                this.AttributeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributesXml
        {
            get
            {
                return this.AttributesXmlField;
            }
            set
            {
                this.AttributesXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountAmountExclTax
        {
            get
            {
                return this.DiscountAmountExclTaxField;
            }
            set
            {
                this.DiscountAmountExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountAmountInclTax
        {
            get
            {
                return this.DiscountAmountInclTaxField;
            }
            set
            {
                this.DiscountAmountInclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ItemWeight
        {
            get
            {
                return this.ItemWeightField;
            }
            set
            {
                this.ItemWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceExclTax
        {
            get
            {
                return this.PriceExclTaxField;
            }
            set
            {
                this.PriceExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceInclTax
        {
            get
            {
                return this.PriceInclTaxField;
            }
            set
            {
                this.PriceInclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU
        {
            get
            {
                return this.SKUField;
            }
            set
            {
                this.SKUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPriceExclTax
        {
            get
            {
                return this.UnitPriceExclTaxField;
            }
            set
            {
                this.UnitPriceExclTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPriceInclTax
        {
            get
            {
                return this.UnitPriceInclTaxField;
            }
            set
            {
                this.UnitPriceInclTaxField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.INopService")]
    public interface INopService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetPaymentMethodCollection", ReplyAction="http://tempuri.org/INopService/GetPaymentMethodCollectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.PaymentMethod[]> GetPaymentMethodCollectionAsync(string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetShippingMethodCollection", ReplyAction="http://tempuri.org/INopService/GetShippingMethodCollectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.ShippingMethod[]> GetShippingMethodCollectionAsync(string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/ProductList", ReplyAction="http://tempuri.org/INopService/ProductListResponse")]
        System.Threading.Tasks.Task<ServiceReference.Products[]> ProductListAsync(string usernameOrEmail, string userPassword, System.Nullable<int> SearchCategoryId, System.Nullable<int> SearchManufacturerId, string SearchProductName, int pageIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/NewProductList", ReplyAction="http://tempuri.org/INopService/NewProductListResponse")]
        System.Threading.Tasks.Task<ServiceReference.Products[]> NewProductListAsync(string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetProductBySku", ReplyAction="http://tempuri.org/INopService/GetProductBySkuResponse")]
        System.Threading.Tasks.Task<ServiceReference.Products[]> GetProductBySkuAsync(string sku, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetProductAttributes", ReplyAction="http://tempuri.org/INopService/GetProductAttributesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> GetProductAttributesAsync(string sku, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetProductAttributesValue", ReplyAction="http://tempuri.org/INopService/GetProductAttributesValueResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> GetProductAttributesValueAsync(string sku, int IdProductAttributes, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetCategoryCollection", ReplyAction="http://tempuri.org/INopService/GetCategoryCollectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.WebServiceCategory[]> GetCategoryCollectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetManufacturerCollection", ReplyAction="http://tempuri.org/INopService/GetManufacturerCollectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.WebServiceManufacturer[]> GetManufacturerCollectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetAddress", ReplyAction="http://tempuri.org/INopService/GetAddressResponse")]
        System.Threading.Tasks.Task<ServiceReference.Address[]> GetAddressAsync(string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/AddNewAddress", ReplyAction="http://tempuri.org/INopService/AddNewAddressResponse")]
        System.Threading.Tasks.Task<ServiceReference.CreateAddressResult> AddNewAddressAsync(ServiceReference.Address address, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/AddToCart", ReplyAction="http://tempuri.org/INopService/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(string sku, int quantity, ServiceReference.ProductAttributes[] pa, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/DeleteFromCart", ReplyAction="http://tempuri.org/INopService/DeleteFromCartResponse")]
        System.Threading.Tasks.Task DeleteFromCartAsync(string sku, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetShoppingCart", ReplyAction="http://tempuri.org/INopService/GetShoppingCartResponse")]
        System.Threading.Tasks.Task<ServiceReference.Cart[]> GetShoppingCartAsync(string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetCountry", ReplyAction="http://tempuri.org/INopService/GetCountryResponse")]
        System.Threading.Tasks.Task<ServiceReference.Country[]> GetCountryAsync(string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetStateProvince", ReplyAction="http://tempuri.org/INopService/GetStateProvinceResponse")]
        System.Threading.Tasks.Task<ServiceReference.StateProvince[]> GetStateProvinceAsync(int CountryId, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/CreateOrder", ReplyAction="http://tempuri.org/INopService/CreateOrderResponse")]
        System.Threading.Tasks.Task<ServiceReference.CreateOrderResult> CreateOrderAsync(string paymentMethodName, string shippingMethodName, int billingAddress, int shippingAddress, string usernameOrEmail, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INopService/GetOrderCollection", ReplyAction="http://tempuri.org/INopService/GetOrderCollectionResponse")]
        System.Threading.Tasks.Task<ServiceReference.WebServiceOrder[]> GetOrderCollectionAsync(System.Nullable<System.DateTime> startDateValue, System.Nullable<System.DateTime> endDateValue, System.Nullable<ServiceReference.OrderStatus> orderStatus, System.Nullable<ServiceReference.PaymentStatus> paymentStatus, System.Nullable<ServiceReference.ShippingStatus> shippingStatus, int pageIndex, string usernameOrEmail, string userPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface INopServiceChannel : ServiceReference.INopService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NopServiceClient : System.ServiceModel.ClientBase<ServiceReference.INopService>, ServiceReference.INopService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NopServiceClient() : 
                base(NopServiceClient.GetDefaultBinding(), NopServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INopService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NopServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NopServiceClient.GetBindingForEndpoint(endpointConfiguration), NopServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NopServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NopServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NopServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NopServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference.PaymentMethod[]> GetPaymentMethodCollectionAsync(string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetPaymentMethodCollectionAsync(usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ShippingMethod[]> GetShippingMethodCollectionAsync(string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetShippingMethodCollectionAsync(usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Products[]> ProductListAsync(string usernameOrEmail, string userPassword, System.Nullable<int> SearchCategoryId, System.Nullable<int> SearchManufacturerId, string SearchProductName, int pageIndex)
        {
            return base.Channel.ProductListAsync(usernameOrEmail, userPassword, SearchCategoryId, SearchManufacturerId, SearchProductName, pageIndex);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Products[]> NewProductListAsync(string usernameOrEmail, string userPassword)
        {
            return base.Channel.NewProductListAsync(usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Products[]> GetProductBySkuAsync(string sku, string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetProductBySkuAsync(sku, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> GetProductAttributesAsync(string sku, string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetProductAttributesAsync(sku, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> GetProductAttributesValueAsync(string sku, int IdProductAttributes, string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetProductAttributesValueAsync(sku, IdProductAttributes, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.WebServiceCategory[]> GetCategoryCollectionAsync()
        {
            return base.Channel.GetCategoryCollectionAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.WebServiceManufacturer[]> GetManufacturerCollectionAsync()
        {
            return base.Channel.GetManufacturerCollectionAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Address[]> GetAddressAsync(string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetAddressAsync(usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CreateAddressResult> AddNewAddressAsync(ServiceReference.Address address, string usernameOrEmail, string userPassword)
        {
            return base.Channel.AddNewAddressAsync(address, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(string sku, int quantity, ServiceReference.ProductAttributes[] pa, string usernameOrEmail, string userPassword)
        {
            return base.Channel.AddToCartAsync(sku, quantity, pa, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task DeleteFromCartAsync(string sku, string usernameOrEmail, string userPassword)
        {
            return base.Channel.DeleteFromCartAsync(sku, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Cart[]> GetShoppingCartAsync(string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetShoppingCartAsync(usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Country[]> GetCountryAsync(string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetCountryAsync(usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.StateProvince[]> GetStateProvinceAsync(int CountryId, string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetStateProvinceAsync(CountryId, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CreateOrderResult> CreateOrderAsync(string paymentMethodName, string shippingMethodName, int billingAddress, int shippingAddress, string usernameOrEmail, string userPassword)
        {
            return base.Channel.CreateOrderAsync(paymentMethodName, shippingMethodName, billingAddress, shippingAddress, usernameOrEmail, userPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.WebServiceOrder[]> GetOrderCollectionAsync(System.Nullable<System.DateTime> startDateValue, System.Nullable<System.DateTime> endDateValue, System.Nullable<ServiceReference.OrderStatus> orderStatus, System.Nullable<ServiceReference.PaymentStatus> paymentStatus, System.Nullable<ServiceReference.ShippingStatus> shippingStatus, int pageIndex, string usernameOrEmail, string userPassword)
        {
            return base.Channel.GetOrderCollectionAsync(startDateValue, endDateValue, orderStatus, paymentStatus, shippingStatus, pageIndex, usernameOrEmail, userPassword);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INopService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INopService))
            {
                return new System.ServiceModel.EndpointAddress("http://demowebshop.tricentis.com/Plugins/Misc.WebServicesCustomer/Remote/NopServi" +
                        "ce.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NopServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INopService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NopServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INopService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INopService,
        }
    }
}
