<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Qty</name>
   <tag></tag>
   <elementGuidId>21047792-d693-4593-b894-61021acf4303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.qty-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8f606183-197d-43e1-999d-8d4f8832c8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-label</value>
      <webElementGuid>cc55496d-ff2f-4af2-9497-335d4c56d08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>addtocart_36_EnteredQuantity</value>
      <webElementGuid>aca35ef2-5258-4a57-9a43-b016548c4224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qty:</value>
      <webElementGuid>c47be7c2-708b-45d7-a2ab-864b62f0b9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-details-form&quot;)/div[1]/div[@class=&quot;product-essential&quot;]/div[@class=&quot;overview&quot;]/div[@class=&quot;add-to-cart&quot;]/div[@class=&quot;add-to-cart-panel&quot;]/label[@class=&quot;qty-label&quot;]</value>
      <webElementGuid>8cab56c0-db92-475b-aec1-8bff49542f64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/label</value>
      <webElementGuid>cd7a02cf-611c-43ea-8a48-bd9b4a8b1f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add your review'])[1]/following::label[1]</value>
      <webElementGuid>85bcbb12-af70-489f-afed-7d950db7ce0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::label[1]</value>
      <webElementGuid>207d82b3-7914-40b9-8f7b-6607c7bd188a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product tags'])[1]/preceding::label[1]</value>
      <webElementGuid>db3fc8d8-41d2-402a-b285-e4e99677db24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cool'])[1]/preceding::label[1]</value>
      <webElementGuid>688e6872-0588-4595-a077-8d725c63a282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Qty:']/parent::*</value>
      <webElementGuid>aa1d6362-8a06-4319-a732-dcce99f99e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d84783ed-3e90-4927-a1b2-5769514daac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Qty:' or . = 'Qty:')]</value>
      <webElementGuid>75c036c3-cbdd-454c-b412-6c99b8aff5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
