<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_addtocart_43.EnteredQuantity</name>
   <tag></tag>
   <elementGuidId>e8a55bb5-9514-4d68-81a4-1983b2e00525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addtocart_43_EnteredQuantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addtocart_43_EnteredQuantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88c0319b-4f5b-4044-9676-ae9d102880ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input valid</value>
      <webElementGuid>2f164aab-8416-4e59-a693-9203f9b3f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3f99e6a-beb1-4f71-bf8c-975ea8300411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Qty must be a number.</value>
      <webElementGuid>c04981b4-d908-4a81-a6dd-76429444363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addtocart_43_EnteredQuantity</value>
      <webElementGuid>5f545aa9-ce72-4dd6-97d2-0d104d42d260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtocart_43.EnteredQuantity</value>
      <webElementGuid>15845cb7-12bd-4093-8482-db7783cdbaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6317c23e-04c7-4e80-a6b0-fdd3abf38c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b02854ec-5fab-4952-bd51-0881fee65096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addtocart_43_EnteredQuantity&quot;)</value>
      <webElementGuid>d15373ef-3eba-41e5-ab24-da6cac3e3409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addtocart_43_EnteredQuantity']</value>
      <webElementGuid>a1ce0b27-b43a-46ba-8de4-8ebf1136e9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/input</value>
      <webElementGuid>edc2f3a6-53f2-4478-b928-ea0c62e7eaa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>618e6c1f-7a54-4d0c-93e4-4dcdb50a5b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addtocart_43_EnteredQuantity' and @name = 'addtocart_43.EnteredQuantity' and @type = 'text']</value>
      <webElementGuid>f5967def-a99b-48b2-8d44-fdb56efe54b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
