<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electronics</name>
   <tag></tag>
   <elementGuidId>da280bd8-3de3-4053-b7f6-ecb3a754cd6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Electronics')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27ad3cea-982f-4519-81c1-2b982a773ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/electronics</value>
      <webElementGuid>ed25cc21-d5fb-4bf3-ac8f-0907f9f62b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>0fc01f0e-419f-4100-8d5c-5da112b28fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Electronics
        </value>
      <webElementGuid>71aeaf15-dc1f-4f47-84e8-8478bbeb047d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;header-menu&quot;]/ul[@class=&quot;top-menu&quot;]/li[3]/a[@class=&quot;hover&quot;]</value>
      <webElementGuid>43dee638-2575-47b1-ae5b-0df9b909cbe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Electronics')]</value>
      <webElementGuid>4b2cefeb-a0a5-4777-8ecb-98db5ad4b2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/electronics')]</value>
      <webElementGuid>ecf29b36-5b62-4ad7-8827-470d07bdc6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
