name: CI Pipeline

env:
  API_USERNAME: ${{ secrets.API_USERNAME }}
  API_PASSWORD: ${{ secrets.API_PASSWORD }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopUnitTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      
      - name: Run tests
        run: dotnet test

  api-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopApiTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      
      - name: Run tests
        run: dotnet test
  
  performance-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopPerformanceTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Run tests
        run: dotnet test

  gui-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopGuiTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      
      - name: Run tests
        run: dotnet test