name: CI Pipeline

env:
  API_USERNAME: ${{ secrets.API_USERNAME }}
  API_PASSWORD: ${{ secrets.API_PASSWORD }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopUnitTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      
      - name: Run tests
        run: dotnet test /p:Include=[*]CostsCalculator /p:CollectCoverage=true /p:Threshold=90 /p:ThresholdType=branch /p:ThresholdStat=minimum /p:CoverletOutputFormat="opencover"

      - name: Generate OpenCover badge
        uses: danpetitt/open-cover-badge-generator-action@v1.0.9
        with:
          path-to-opencover-xml: WebShopUnitTests/coverage.opencover.xml
          path-to-badges: ./
          minimum-coverage: 90
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  api-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopApiTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      
      - name: Run tests
        run: dotnet test
  
  performance-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopPerformanceTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Run tests
        run: dotnet test

  gui-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Katalon Studio on 
      run: |
        # Download and extract Katalon Studio Engine
        curl -L "https://backend.katalon.com/download-lastest-version?platform=mac_64&type_download=re" -o engine.tar.gz
        tar -xf engine.tar.gz
        # Run Katalon Studio Engine
        ls -lah
        cd "Katalon_Studio_Engine*"
        cd "Katalon Studio Engine.app/Contents/MacOS"
        chmod +x katalonc
        
        ./katalonc -noSplash -runMode=console -projectPath="../../../../WebShopGuiTests" -retry=0 -testSuitePath="Test Suites/Test Suite" -browserType="saucelabs_second" -executionProfile="default" -apiKey="${{ secrets.KATALON_API_KEY }}" -testOpsProjectId=1151115 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true