name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
  
  performance-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WebShopPerformanceTests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test

  gui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          
    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build the solution
    #   run: dotnet build --configuration Release --no-restore

    # Add steps to run tests using the testing tools or suites of your choice.
    # For example, if you decide to use NUnit for unit testing:
    #
    # - name: Run unit tests
    #   run: dotnet test --logger "trx;LogFileName=TestResults.trx" --configuration Release --no-build

    # - name: Run GUI tests
    #   run: # Add command to run GUI tests

    # - name: Run performance tests
    #   run: # Add command to run performance tests

    # - name: Run API tests
    #   run: # Add command to run API tests
